// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cmd/blog/app/codec.proto

package blog

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	metro "github.com/iov-one/blog-tutorial/x/metro"
	migration "github.com/iov-one/weave/migration"
	cash "github.com/iov-one/weave/x/cash"
	multisig "github.com/iov-one/weave/x/multisig"
	sigs "github.com/iov-one/weave/x/sigs"
	validators "github.com/iov-one/weave/x/validators"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Tx contains the message
// When extending Tx, follow the rules:
// - Range 1-50 is reserved for middlewares,
// - Range 51-inf is reserved for different message types,
// - Keep the same numbers for the same message types in weave based applications to
//   sustain compatibility between blockchains. For example, FeeInfo field is used by
//   both and indexed at first position. Skip unused fields (leave index unused or
//   comment out for clarity).
// When there is a gap in message sequence numbers - that most likely means some
// old fields got deprecated. This is done to maintain binary compatibility.
type Tx struct {
	// Enables coin.GetFees()
	Fees *cash.FeeInfo `protobuf:"bytes,1,opt,name=fees,proto3" json:"fees,omitempty"`
	//StdSignature represents the signature, the identity of the signer
	// (the Pubkey), and a sequence number to prevent replay attacks.
	Signatures []*sigs.StdSignature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// ID of a multisig contract.
	Multisig [][]byte `protobuf:"bytes,4,rep,name=multisig,proto3" json:"multisig,omitempty"`
	// sum defines over all allowed messages on this chain.
	//
	// Types that are valid to be assigned to Sum:
	//	*Tx_CashSendMsg
	//	*Tx_MultisigCreateMsg
	//	*Tx_MultisigUpdateMsg
	//	*Tx_ValidatorsApplyDiffMsg
	//	*Tx_ExecuteBatchMsg
	//	*Tx_MigrationUpgradeSchemaMsg
	//	*Tx_MetroRegisterPassengerMsg
	//	*Tx_MetroTrainArriveStationEventMsg
	Sum isTx_Sum `protobuf_oneof:"sum"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_96adc38df3c83d28, []int{0}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return m.Size()
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

type isTx_Sum interface {
	isTx_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Tx_CashSendMsg struct {
	CashSendMsg *cash.SendMsg `protobuf:"bytes,51,opt,name=cash_send_msg,json=cashSendMsg,proto3,oneof"`
}
type Tx_MultisigCreateMsg struct {
	MultisigCreateMsg *multisig.CreateMsg `protobuf:"bytes,56,opt,name=multisig_create_msg,json=multisigCreateMsg,proto3,oneof"`
}
type Tx_MultisigUpdateMsg struct {
	MultisigUpdateMsg *multisig.UpdateMsg `protobuf:"bytes,57,opt,name=multisig_update_msg,json=multisigUpdateMsg,proto3,oneof"`
}
type Tx_ValidatorsApplyDiffMsg struct {
	ValidatorsApplyDiffMsg *validators.ApplyDiffMsg `protobuf:"bytes,58,opt,name=validators_apply_diff_msg,json=validatorsApplyDiffMsg,proto3,oneof"`
}
type Tx_ExecuteBatchMsg struct {
	ExecuteBatchMsg *ExecuteBatchMsg `protobuf:"bytes,60,opt,name=execute_batch_msg,json=executeBatchMsg,proto3,oneof"`
}
type Tx_MigrationUpgradeSchemaMsg struct {
	MigrationUpgradeSchemaMsg *migration.UpgradeSchemaMsg `protobuf:"bytes,69,opt,name=migration_upgrade_schema_msg,json=migrationUpgradeSchemaMsg,proto3,oneof"`
}
type Tx_MetroRegisterPassengerMsg struct {
	MetroRegisterPassengerMsg *metro.RegisterPassengerMsg `protobuf:"bytes,70,opt,name=metro_register_passenger_msg,json=metroRegisterPassengerMsg,proto3,oneof"`
}
type Tx_MetroTrainArriveStationEventMsg struct {
	MetroTrainArriveStationEventMsg *metro.TrainArriveStationEventMsg `protobuf:"bytes,71,opt,name=metro_train_arrive_station_event_msg,json=metroTrainArriveStationEventMsg,proto3,oneof"`
}

func (*Tx_CashSendMsg) isTx_Sum()                     {}
func (*Tx_MultisigCreateMsg) isTx_Sum()               {}
func (*Tx_MultisigUpdateMsg) isTx_Sum()               {}
func (*Tx_ValidatorsApplyDiffMsg) isTx_Sum()          {}
func (*Tx_ExecuteBatchMsg) isTx_Sum()                 {}
func (*Tx_MigrationUpgradeSchemaMsg) isTx_Sum()       {}
func (*Tx_MetroRegisterPassengerMsg) isTx_Sum()       {}
func (*Tx_MetroTrainArriveStationEventMsg) isTx_Sum() {}

func (m *Tx) GetSum() isTx_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Tx) GetFees() *cash.FeeInfo {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *Tx) GetSignatures() []*sigs.StdSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Tx) GetMultisig() [][]byte {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *Tx) GetCashSendMsg() *cash.SendMsg {
	if x, ok := m.GetSum().(*Tx_CashSendMsg); ok {
		return x.CashSendMsg
	}
	return nil
}

func (m *Tx) GetMultisigCreateMsg() *multisig.CreateMsg {
	if x, ok := m.GetSum().(*Tx_MultisigCreateMsg); ok {
		return x.MultisigCreateMsg
	}
	return nil
}

func (m *Tx) GetMultisigUpdateMsg() *multisig.UpdateMsg {
	if x, ok := m.GetSum().(*Tx_MultisigUpdateMsg); ok {
		return x.MultisigUpdateMsg
	}
	return nil
}

func (m *Tx) GetValidatorsApplyDiffMsg() *validators.ApplyDiffMsg {
	if x, ok := m.GetSum().(*Tx_ValidatorsApplyDiffMsg); ok {
		return x.ValidatorsApplyDiffMsg
	}
	return nil
}

func (m *Tx) GetExecuteBatchMsg() *ExecuteBatchMsg {
	if x, ok := m.GetSum().(*Tx_ExecuteBatchMsg); ok {
		return x.ExecuteBatchMsg
	}
	return nil
}

func (m *Tx) GetMigrationUpgradeSchemaMsg() *migration.UpgradeSchemaMsg {
	if x, ok := m.GetSum().(*Tx_MigrationUpgradeSchemaMsg); ok {
		return x.MigrationUpgradeSchemaMsg
	}
	return nil
}

func (m *Tx) GetMetroRegisterPassengerMsg() *metro.RegisterPassengerMsg {
	if x, ok := m.GetSum().(*Tx_MetroRegisterPassengerMsg); ok {
		return x.MetroRegisterPassengerMsg
	}
	return nil
}

func (m *Tx) GetMetroTrainArriveStationEventMsg() *metro.TrainArriveStationEventMsg {
	if x, ok := m.GetSum().(*Tx_MetroTrainArriveStationEventMsg); ok {
		return x.MetroTrainArriveStationEventMsg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Tx) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Tx_OneofMarshaler, _Tx_OneofUnmarshaler, _Tx_OneofSizer, []interface{}{
		(*Tx_CashSendMsg)(nil),
		(*Tx_MultisigCreateMsg)(nil),
		(*Tx_MultisigUpdateMsg)(nil),
		(*Tx_ValidatorsApplyDiffMsg)(nil),
		(*Tx_ExecuteBatchMsg)(nil),
		(*Tx_MigrationUpgradeSchemaMsg)(nil),
		(*Tx_MetroRegisterPassengerMsg)(nil),
		(*Tx_MetroTrainArriveStationEventMsg)(nil),
	}
}

func _Tx_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Tx)
	// sum
	switch x := m.Sum.(type) {
	case *Tx_CashSendMsg:
		_ = b.EncodeVarint(51<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CashSendMsg); err != nil {
			return err
		}
	case *Tx_MultisigCreateMsg:
		_ = b.EncodeVarint(56<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MultisigCreateMsg); err != nil {
			return err
		}
	case *Tx_MultisigUpdateMsg:
		_ = b.EncodeVarint(57<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MultisigUpdateMsg); err != nil {
			return err
		}
	case *Tx_ValidatorsApplyDiffMsg:
		_ = b.EncodeVarint(58<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ValidatorsApplyDiffMsg); err != nil {
			return err
		}
	case *Tx_ExecuteBatchMsg:
		_ = b.EncodeVarint(60<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteBatchMsg); err != nil {
			return err
		}
	case *Tx_MigrationUpgradeSchemaMsg:
		_ = b.EncodeVarint(69<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MigrationUpgradeSchemaMsg); err != nil {
			return err
		}
	case *Tx_MetroRegisterPassengerMsg:
		_ = b.EncodeVarint(70<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MetroRegisterPassengerMsg); err != nil {
			return err
		}
	case *Tx_MetroTrainArriveStationEventMsg:
		_ = b.EncodeVarint(71<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MetroTrainArriveStationEventMsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Tx.Sum has unexpected type %T", x)
	}
	return nil
}

func _Tx_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Tx)
	switch tag {
	case 51: // sum.cash_send_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(cash.SendMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_CashSendMsg{msg}
		return true, err
	case 56: // sum.multisig_create_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(multisig.CreateMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_MultisigCreateMsg{msg}
		return true, err
	case 57: // sum.multisig_update_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(multisig.UpdateMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_MultisigUpdateMsg{msg}
		return true, err
	case 58: // sum.validators_apply_diff_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(validators.ApplyDiffMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_ValidatorsApplyDiffMsg{msg}
		return true, err
	case 60: // sum.execute_batch_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteBatchMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_ExecuteBatchMsg{msg}
		return true, err
	case 69: // sum.migration_upgrade_schema_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(migration.UpgradeSchemaMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_MigrationUpgradeSchemaMsg{msg}
		return true, err
	case 70: // sum.metro_register_passenger_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(metro.RegisterPassengerMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_MetroRegisterPassengerMsg{msg}
		return true, err
	case 71: // sum.metro_train_arrive_station_event_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(metro.TrainArriveStationEventMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &Tx_MetroTrainArriveStationEventMsg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Tx_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Tx)
	// sum
	switch x := m.Sum.(type) {
	case *Tx_CashSendMsg:
		s := proto.Size(x.CashSendMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_MultisigCreateMsg:
		s := proto.Size(x.MultisigCreateMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_MultisigUpdateMsg:
		s := proto.Size(x.MultisigUpdateMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_ValidatorsApplyDiffMsg:
		s := proto.Size(x.ValidatorsApplyDiffMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_ExecuteBatchMsg:
		s := proto.Size(x.ExecuteBatchMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_MigrationUpgradeSchemaMsg:
		s := proto.Size(x.MigrationUpgradeSchemaMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_MetroRegisterPassengerMsg:
		s := proto.Size(x.MetroRegisterPassengerMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Tx_MetroTrainArriveStationEventMsg:
		s := proto.Size(x.MetroTrainArriveStationEventMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// ExecuteBatchMsg encapsulates multiple messages to support batch transaction
type ExecuteBatchMsg struct {
	Messages []ExecuteBatchMsg_Union `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages"`
}

func (m *ExecuteBatchMsg) Reset()         { *m = ExecuteBatchMsg{} }
func (m *ExecuteBatchMsg) String() string { return proto.CompactTextString(m) }
func (*ExecuteBatchMsg) ProtoMessage()    {}
func (*ExecuteBatchMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_96adc38df3c83d28, []int{1}
}
func (m *ExecuteBatchMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecuteBatchMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecuteBatchMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecuteBatchMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteBatchMsg.Merge(m, src)
}
func (m *ExecuteBatchMsg) XXX_Size() int {
	return m.Size()
}
func (m *ExecuteBatchMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteBatchMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteBatchMsg proto.InternalMessageInfo

func (m *ExecuteBatchMsg) GetMessages() []ExecuteBatchMsg_Union {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ExecuteBatchMsg_Union struct {
	// No recursive batches!
	//
	// Types that are valid to be assigned to Sum:
	//	*ExecuteBatchMsg_Union_CashSendMsg
	//	*ExecuteBatchMsg_Union_MultisigCreateMsg
	//	*ExecuteBatchMsg_Union_MultisigUpdateMsg
	Sum isExecuteBatchMsg_Union_Sum `protobuf_oneof:"sum"`
}

func (m *ExecuteBatchMsg_Union) Reset()         { *m = ExecuteBatchMsg_Union{} }
func (m *ExecuteBatchMsg_Union) String() string { return proto.CompactTextString(m) }
func (*ExecuteBatchMsg_Union) ProtoMessage()    {}
func (*ExecuteBatchMsg_Union) Descriptor() ([]byte, []int) {
	return fileDescriptor_96adc38df3c83d28, []int{1, 0}
}
func (m *ExecuteBatchMsg_Union) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecuteBatchMsg_Union) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecuteBatchMsg_Union.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecuteBatchMsg_Union) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteBatchMsg_Union.Merge(m, src)
}
func (m *ExecuteBatchMsg_Union) XXX_Size() int {
	return m.Size()
}
func (m *ExecuteBatchMsg_Union) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteBatchMsg_Union.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteBatchMsg_Union proto.InternalMessageInfo

type isExecuteBatchMsg_Union_Sum interface {
	isExecuteBatchMsg_Union_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ExecuteBatchMsg_Union_CashSendMsg struct {
	CashSendMsg *cash.SendMsg `protobuf:"bytes,51,opt,name=cash_send_msg,json=cashSendMsg,proto3,oneof"`
}
type ExecuteBatchMsg_Union_MultisigCreateMsg struct {
	MultisigCreateMsg *multisig.CreateMsg `protobuf:"bytes,56,opt,name=multisig_create_msg,json=multisigCreateMsg,proto3,oneof"`
}
type ExecuteBatchMsg_Union_MultisigUpdateMsg struct {
	MultisigUpdateMsg *multisig.UpdateMsg `protobuf:"bytes,57,opt,name=multisig_update_msg,json=multisigUpdateMsg,proto3,oneof"`
}

func (*ExecuteBatchMsg_Union_CashSendMsg) isExecuteBatchMsg_Union_Sum()       {}
func (*ExecuteBatchMsg_Union_MultisigCreateMsg) isExecuteBatchMsg_Union_Sum() {}
func (*ExecuteBatchMsg_Union_MultisigUpdateMsg) isExecuteBatchMsg_Union_Sum() {}

func (m *ExecuteBatchMsg_Union) GetSum() isExecuteBatchMsg_Union_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *ExecuteBatchMsg_Union) GetCashSendMsg() *cash.SendMsg {
	if x, ok := m.GetSum().(*ExecuteBatchMsg_Union_CashSendMsg); ok {
		return x.CashSendMsg
	}
	return nil
}

func (m *ExecuteBatchMsg_Union) GetMultisigCreateMsg() *multisig.CreateMsg {
	if x, ok := m.GetSum().(*ExecuteBatchMsg_Union_MultisigCreateMsg); ok {
		return x.MultisigCreateMsg
	}
	return nil
}

func (m *ExecuteBatchMsg_Union) GetMultisigUpdateMsg() *multisig.UpdateMsg {
	if x, ok := m.GetSum().(*ExecuteBatchMsg_Union_MultisigUpdateMsg); ok {
		return x.MultisigUpdateMsg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ExecuteBatchMsg_Union) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ExecuteBatchMsg_Union_OneofMarshaler, _ExecuteBatchMsg_Union_OneofUnmarshaler, _ExecuteBatchMsg_Union_OneofSizer, []interface{}{
		(*ExecuteBatchMsg_Union_CashSendMsg)(nil),
		(*ExecuteBatchMsg_Union_MultisigCreateMsg)(nil),
		(*ExecuteBatchMsg_Union_MultisigUpdateMsg)(nil),
	}
}

func _ExecuteBatchMsg_Union_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ExecuteBatchMsg_Union)
	// sum
	switch x := m.Sum.(type) {
	case *ExecuteBatchMsg_Union_CashSendMsg:
		_ = b.EncodeVarint(51<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CashSendMsg); err != nil {
			return err
		}
	case *ExecuteBatchMsg_Union_MultisigCreateMsg:
		_ = b.EncodeVarint(56<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MultisigCreateMsg); err != nil {
			return err
		}
	case *ExecuteBatchMsg_Union_MultisigUpdateMsg:
		_ = b.EncodeVarint(57<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MultisigUpdateMsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ExecuteBatchMsg_Union.Sum has unexpected type %T", x)
	}
	return nil
}

func _ExecuteBatchMsg_Union_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ExecuteBatchMsg_Union)
	switch tag {
	case 51: // sum.cash_send_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(cash.SendMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &ExecuteBatchMsg_Union_CashSendMsg{msg}
		return true, err
	case 56: // sum.multisig_create_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(multisig.CreateMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &ExecuteBatchMsg_Union_MultisigCreateMsg{msg}
		return true, err
	case 57: // sum.multisig_update_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(multisig.UpdateMsg)
		err := b.DecodeMessage(msg)
		m.Sum = &ExecuteBatchMsg_Union_MultisigUpdateMsg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ExecuteBatchMsg_Union_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ExecuteBatchMsg_Union)
	// sum
	switch x := m.Sum.(type) {
	case *ExecuteBatchMsg_Union_CashSendMsg:
		s := proto.Size(x.CashSendMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExecuteBatchMsg_Union_MultisigCreateMsg:
		s := proto.Size(x.MultisigCreateMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExecuteBatchMsg_Union_MultisigUpdateMsg:
		s := proto.Size(x.MultisigUpdateMsg)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Tx)(nil), "blog.Tx")
	proto.RegisterType((*ExecuteBatchMsg)(nil), "blog.ExecuteBatchMsg")
	proto.RegisterType((*ExecuteBatchMsg_Union)(nil), "blog.ExecuteBatchMsg.Union")
}

func init() { proto.RegisterFile("cmd/blog/app/codec.proto", fileDescriptor_96adc38df3c83d28) }

var fileDescriptor_96adc38df3c83d28 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0x87, 0xdb, 0xb5, 0x9b, 0x26, 0x8f, 0x69, 0x9a, 0x07, 0x28, 0x2b, 0xa8, 0xfb, 0x23, 0x0e,
	0x93, 0x10, 0x8e, 0xd8, 0x2e, 0x80, 0xe0, 0xb0, 0x8e, 0x0e, 0x38, 0x20, 0xa1, 0x74, 0xbd, 0x62,
	0xb9, 0xc9, 0x1b, 0xd7, 0x52, 0x13, 0x47, 0xb6, 0x53, 0xca, 0xb7, 0x80, 0xef, 0xc0, 0x87, 0xd9,
	0x71, 0xdc, 0x38, 0x21, 0xb4, 0x7d, 0x11, 0x64, 0xa7, 0xc9, 0xda, 0x6a, 0x9b, 0x38, 0x73, 0x8b,
	0xdf, 0xdf, 0xf3, 0x3e, 0x6f, 0xed, 0xb8, 0x41, 0x5e, 0x98, 0x44, 0xfe, 0x60, 0x24, 0xb9, 0xcf,
	0xb2, 0xcc, 0x0f, 0x65, 0x04, 0x21, 0xc9, 0x94, 0x34, 0x12, 0x37, 0x6d, 0xb5, 0x45, 0xb8, 0x30,
	0xc3, 0x7c, 0x40, 0x42, 0x99, 0xf8, 0x42, 0x8e, 0x9f, 0xc9, 0x14, 0xfc, 0x2f, 0xc0, 0xc6, 0xe0,
	0x27, 0x82, 0x2b, 0x66, 0x84, 0x4c, 0x67, 0xbb, 0x5a, 0x4f, 0x6f, 0xe5, 0x27, 0x7e, 0xc8, 0xf4,
	0x70, 0x0e, 0xf6, 0xef, 0x80, 0x93, 0x7c, 0x64, 0x84, 0x16, 0xfc, 0x9f, 0xed, 0x5a, 0x70, 0x3d,
	0x07, 0x3f, 0xbf, 0x03, 0x1e, 0xb3, 0x91, 0x88, 0x98, 0x91, 0x6a, 0xbe, 0xe5, 0x3e, 0x97, 0x5c,
	0xba, 0x47, 0xdf, 0x3e, 0x4d, 0xab, 0x5b, 0x13, 0x3f, 0x01, 0xa3, 0xe4, 0x2c, 0xba, 0xff, 0x7d,
	0x05, 0x2d, 0x9d, 0x4d, 0xf0, 0x1e, 0x6a, 0xc6, 0x00, 0xda, 0xab, 0xef, 0xd6, 0x0f, 0xd6, 0x0e,
	0xd7, 0x89, 0xdd, 0x23, 0x39, 0x05, 0xf8, 0x90, 0xc6, 0x32, 0x70, 0x11, 0x3e, 0x44, 0x48, 0x0b,
	0x9e, 0x32, 0x93, 0x2b, 0xd0, 0xde, 0xd2, 0x6e, 0xe3, 0x60, 0xed, 0x10, 0x13, 0xfb, 0x73, 0x49,
	0xcf, 0x44, 0xbd, 0x32, 0x0a, 0x66, 0x28, 0xdc, 0x42, 0xab, 0xe5, 0x01, 0x78, 0xcd, 0xdd, 0xc6,
	0xc1, 0xbd, 0xa0, 0x5a, 0xe3, 0x23, 0xb4, 0x6e, 0xa7, 0x50, 0x0d, 0x69, 0x44, 0x13, 0xcd, 0xbd,
	0xa3, 0xd9, 0xd9, 0x3d, 0x48, 0xa3, 0x8f, 0x9a, 0xbf, 0xaf, 0x05, 0x6b, 0x76, 0x3d, 0x5d, 0xe2,
	0x2e, 0xda, 0x2a, 0x05, 0x34, 0x54, 0xc0, 0x0c, 0xb8, 0xd6, 0x17, 0xae, 0x75, 0x8b, 0x94, 0x19,
	0x39, 0x71, 0x59, 0x21, 0xd8, 0x2c, 0xab, 0x55, 0x71, 0x4e, 0x93, 0x67, 0x51, 0xa9, 0x79, 0xb9,
	0xa8, 0xe9, 0xbb, 0x6c, 0x41, 0x53, 0x15, 0x71, 0x1f, 0x6d, 0x5f, 0xbf, 0x01, 0xca, 0xb2, 0x6c,
	0xf4, 0x95, 0x46, 0x22, 0x8e, 0x9d, 0xec, 0x95, 0x93, 0x79, 0xe4, 0x9a, 0x20, 0xc7, 0x96, 0x78,
	0x2b, 0xe2, 0xb8, 0x30, 0x3e, 0xbc, 0x8e, 0x66, 0x13, 0x7c, 0x82, 0x36, 0x61, 0x02, 0x61, 0x6e,
	0x80, 0x0e, 0x98, 0x09, 0x87, 0x4e, 0xf7, 0xda, 0xe9, 0x1e, 0x10, 0x7b, 0x9d, 0x49, 0xb7, 0x88,
	0x3b, 0x36, 0x2d, 0x5c, 0x1b, 0x30, 0x5f, 0xc2, 0x9f, 0xd1, 0xe3, 0xea, 0x6a, 0xd3, 0x3c, 0xe3,
	0x8a, 0x45, 0x40, 0x75, 0x38, 0x84, 0x84, 0x39, 0x5f, 0xd7, 0xf9, 0x1e, 0x91, 0x0a, 0x22, 0xfd,
	0x02, 0xea, 0x39, 0xa6, 0xb0, 0x6e, 0x57, 0xe9, 0x62, 0xe8, 0xfc, 0xf6, 0x36, 0x51, 0x05, 0x5c,
	0x68, 0x03, 0x8a, 0x66, 0x4c, 0x6b, 0x48, 0x39, 0x28, 0xe7, 0x3f, 0x2d, 0xfd, 0x16, 0x22, 0xc1,
	0x14, 0xfa, 0x54, 0x32, 0xa5, 0xdf, 0xa6, 0x37, 0x85, 0x58, 0xa1, 0x27, 0x85, 0xdf, 0x28, 0x26,
	0x52, 0xca, 0x94, 0x12, 0x63, 0xa0, 0xda, 0x14, 0x1b, 0x82, 0x31, 0xa4, 0xc6, 0xcd, 0x79, 0xe7,
	0xe6, 0xec, 0x4d, 0xe7, 0x9c, 0x59, 0xf8, 0xd8, 0xb1, 0xbd, 0x02, 0xed, 0x5a, 0xb2, 0x98, 0xb6,
	0xe3, 0x98, 0xdb, 0x91, 0xce, 0x32, 0x6a, 0xe8, 0x3c, 0xd9, 0xff, 0xb1, 0x84, 0x36, 0x16, 0x4e,
	0x18, 0xbf, 0x41, 0xab, 0x09, 0x68, 0xcd, 0xb8, 0xfb, 0x93, 0x34, 0xdc, 0xd6, 0x6e, 0x7a, 0x15,
	0xa4, 0x9f, 0x0a, 0x99, 0x76, 0x9a, 0xe7, 0xbf, 0x77, 0x6a, 0x41, 0xd5, 0xd2, 0xfa, 0x59, 0x47,
	0xcb, 0x2e, 0xf9, 0x0f, 0xae, 0xfd, 0xf4, 0x98, 0x3a, 0xde, 0xf9, 0x65, 0xbb, 0x7e, 0x71, 0xd9,
	0xae, 0xff, 0xb9, 0x6c, 0xd7, 0xbf, 0x5d, 0xb5, 0x6b, 0x17, 0x57, 0xed, 0xda, 0xaf, 0xab, 0x76,
	0x6d, 0xb0, 0xe2, 0xbe, 0x2d, 0x47, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x31, 0x90, 0xa6, 0x87,
	0x96, 0x05, 0x00, 0x00,
}

func (m *Tx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tx) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Fees != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.Fees.Size()))
		n1, err := m.Fees.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Signatures) > 0 {
		for _, msg := range m.Signatures {
			dAtA[i] = 0x12
			i++
			i = encodeVarintCodec(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Multisig) > 0 {
		for _, b := range m.Multisig {
			dAtA[i] = 0x22
			i++
			i = encodeVarintCodec(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if m.Sum != nil {
		nn2, err := m.Sum.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn2
	}
	return i, nil
}

func (m *Tx_CashSendMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CashSendMsg != nil {
		dAtA[i] = 0x9a
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.CashSendMsg.Size()))
		n3, err := m.CashSendMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}
func (m *Tx_MultisigCreateMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MultisigCreateMsg != nil {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MultisigCreateMsg.Size()))
		n4, err := m.MultisigCreateMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}
func (m *Tx_MultisigUpdateMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MultisigUpdateMsg != nil {
		dAtA[i] = 0xca
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MultisigUpdateMsg.Size()))
		n5, err := m.MultisigUpdateMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}
func (m *Tx_ValidatorsApplyDiffMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.ValidatorsApplyDiffMsg != nil {
		dAtA[i] = 0xd2
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.ValidatorsApplyDiffMsg.Size()))
		n6, err := m.ValidatorsApplyDiffMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}
func (m *Tx_ExecuteBatchMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.ExecuteBatchMsg != nil {
		dAtA[i] = 0xe2
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.ExecuteBatchMsg.Size()))
		n7, err := m.ExecuteBatchMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}
func (m *Tx_MigrationUpgradeSchemaMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MigrationUpgradeSchemaMsg != nil {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x4
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MigrationUpgradeSchemaMsg.Size()))
		n8, err := m.MigrationUpgradeSchemaMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}
func (m *Tx_MetroRegisterPassengerMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MetroRegisterPassengerMsg != nil {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x4
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MetroRegisterPassengerMsg.Size()))
		n9, err := m.MetroRegisterPassengerMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	return i, nil
}
func (m *Tx_MetroTrainArriveStationEventMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MetroTrainArriveStationEventMsg != nil {
		dAtA[i] = 0xba
		i++
		dAtA[i] = 0x4
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MetroTrainArriveStationEventMsg.Size()))
		n10, err := m.MetroTrainArriveStationEventMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	return i, nil
}
func (m *ExecuteBatchMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecuteBatchMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, msg := range m.Messages {
			dAtA[i] = 0xa
			i++
			i = encodeVarintCodec(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ExecuteBatchMsg_Union) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecuteBatchMsg_Union) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		nn11, err := m.Sum.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn11
	}
	return i, nil
}

func (m *ExecuteBatchMsg_Union_CashSendMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CashSendMsg != nil {
		dAtA[i] = 0x9a
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.CashSendMsg.Size()))
		n12, err := m.CashSendMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	return i, nil
}
func (m *ExecuteBatchMsg_Union_MultisigCreateMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MultisigCreateMsg != nil {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MultisigCreateMsg.Size()))
		n13, err := m.MultisigCreateMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	return i, nil
}
func (m *ExecuteBatchMsg_Union_MultisigUpdateMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.MultisigUpdateMsg != nil {
		dAtA[i] = 0xca
		i++
		dAtA[i] = 0x3
		i++
		i = encodeVarintCodec(dAtA, i, uint64(m.MultisigUpdateMsg.Size()))
		n14, err := m.MultisigUpdateMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	return i, nil
}
func encodeVarintCodec(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Tx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Fees != nil {
		l = m.Fees.Size()
		n += 1 + l + sovCodec(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovCodec(uint64(l))
		}
	}
	if len(m.Multisig) > 0 {
		for _, b := range m.Multisig {
			l = len(b)
			n += 1 + l + sovCodec(uint64(l))
		}
	}
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *Tx_CashSendMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CashSendMsg != nil {
		l = m.CashSendMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_MultisigCreateMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MultisigCreateMsg != nil {
		l = m.MultisigCreateMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_MultisigUpdateMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MultisigUpdateMsg != nil {
		l = m.MultisigUpdateMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_ValidatorsApplyDiffMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidatorsApplyDiffMsg != nil {
		l = m.ValidatorsApplyDiffMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_ExecuteBatchMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExecuteBatchMsg != nil {
		l = m.ExecuteBatchMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_MigrationUpgradeSchemaMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MigrationUpgradeSchemaMsg != nil {
		l = m.MigrationUpgradeSchemaMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_MetroRegisterPassengerMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MetroRegisterPassengerMsg != nil {
		l = m.MetroRegisterPassengerMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *Tx_MetroTrainArriveStationEventMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MetroTrainArriveStationEventMsg != nil {
		l = m.MetroTrainArriveStationEventMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *ExecuteBatchMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovCodec(uint64(l))
		}
	}
	return n
}

func (m *ExecuteBatchMsg_Union) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *ExecuteBatchMsg_Union_CashSendMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CashSendMsg != nil {
		l = m.CashSendMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *ExecuteBatchMsg_Union_MultisigCreateMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MultisigCreateMsg != nil {
		l = m.MultisigCreateMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}
func (m *ExecuteBatchMsg_Union_MultisigUpdateMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MultisigUpdateMsg != nil {
		l = m.MultisigUpdateMsg.Size()
		n += 2 + l + sovCodec(uint64(l))
	}
	return n
}

func sovCodec(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCodec(x uint64) (n int) {
	return sovCodec(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Tx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCodec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fees == nil {
				m.Fees = &cash.FeeInfo{}
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, &sigs.StdSignature{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Multisig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Multisig = append(m.Multisig, make([]byte, postIndex-iNdEx))
			copy(m.Multisig[len(m.Multisig)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 51:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CashSendMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &cash.SendMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_CashSendMsg{v}
			iNdEx = postIndex
		case 56:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigCreateMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &multisig.CreateMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_MultisigCreateMsg{v}
			iNdEx = postIndex
		case 57:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigUpdateMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &multisig.UpdateMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_MultisigUpdateMsg{v}
			iNdEx = postIndex
		case 58:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorsApplyDiffMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &validators.ApplyDiffMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_ValidatorsApplyDiffMsg{v}
			iNdEx = postIndex
		case 60:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteBatchMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ExecuteBatchMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_ExecuteBatchMsg{v}
			iNdEx = postIndex
		case 69:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationUpgradeSchemaMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &migration.UpgradeSchemaMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_MigrationUpgradeSchemaMsg{v}
			iNdEx = postIndex
		case 70:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetroRegisterPassengerMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &metro.RegisterPassengerMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_MetroRegisterPassengerMsg{v}
			iNdEx = postIndex
		case 71:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetroTrainArriveStationEventMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &metro.TrainArriveStationEventMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Tx_MetroTrainArriveStationEventMsg{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCodec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCodec
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCodec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecuteBatchMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCodec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecuteBatchMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecuteBatchMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, ExecuteBatchMsg_Union{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCodec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCodec
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCodec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecuteBatchMsg_Union) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCodec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Union: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Union: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 51:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CashSendMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &cash.SendMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &ExecuteBatchMsg_Union_CashSendMsg{v}
			iNdEx = postIndex
		case 56:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigCreateMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &multisig.CreateMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &ExecuteBatchMsg_Union_MultisigCreateMsg{v}
			iNdEx = postIndex
		case 57:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigUpdateMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &multisig.UpdateMsg{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &ExecuteBatchMsg_Union_MultisigUpdateMsg{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCodec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCodec
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCodec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCodec(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCodec
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCodec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCodec
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthCodec
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCodec
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCodec(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthCodec
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCodec = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCodec   = fmt.Errorf("proto: integer overflow")
)
